### ISSUE TITLE
Port AcControl Arduino to RaspberryPi

### ISSUE THREAD

**Issue by guilhermetk** [dpressle/MySensors#2]
Hello! I Already have a raspberry pi running as my data center AC controller, but recently I installed another AC, Gree with an YB1FA remote control, and I couldn't get around to replicate it with neither Lirc on raspberry or IRRemote on Arduino. Just found your library and tested it, works perfectly! But, as my current setup runs on raspberry I would like to port the code to run on it. I basically have lirc config files and use irsend to send the codes to the ACs. My understanding of IR is limited, I don't know exactly how to start, so I would like to know if this is something you help pointing me the right direction!

Didn't know any other way to reach you, thats why I'm opening a issue.

Thanks in advance!

**Comment by dpressle** [comment]
I am not sure about this, the thing is that AC remote works different then TV remote it sends all statuses each time you press a button, so for example if you press the fan button the remote sends the power status the mode the temp and so on.
The tricy part of all this is that there is a checksum to calculate on each command, this is why i have all this code for, so for each command i want to send i calculate the whole command and the checksum.

As far as i know lirc can only record and then send commands it cannot calculate checksum, so i am not sure how it can be done in lirc.

Another way is maybe to compile the code for linux library and use it some how, but i never done it before.

I hope this was helpfull.

**Comment by guilhermetk** [comment]
Didn't know about this lirc limitation, will follow from this point and study the alternatives to that! Thank you very much!
